module.exports = '''
                 <h2>Why do I need to tell you my name and sign-in to Zooniverse?</h2>
                 <p>Providing that the orchid can by positively identified (or ‘verified’), then your photo and the additional information that you upload will form a ‘biological record’. A biological record must contain four essential pieces of information: what was found, where it was found, when it was found and who found it. This is why we ask you for your name; it ensures that your orchid sighting can contribute to our shared understanding of the UK’s orchids for decades to come.</p>
                 <p>We ask you to sign-in so that we have a contact email associated with your observation. You will only be contacted if an expert from the Botanical Society of the British Isles wishes to find out more about your photograph, for example to learn more about where you found it, if it is an exciting or unexpected find.</p>
                 <h2>How will my data be managed?</h2>
                 <p>Your images and associated data will be stored by the Biological Records Centre within a version of the <a href="http://www.brc.ac.uk/irecord/">iRecord</a> database for the duration of this project. <a href="http://www.brc.ac.uk/irecord/terms_of_use">See here for terms of use</a>. The data that you upload will also be transferred to the Zooniverse database for classification. You can see the <a href="http://www.zooniverse.org/privacy">Zooniverse privacy policy here</a>. Photo and location data will be made visible within the IDENTIFY tab (none of your personal data will be shown).</p> 
                 <p>Note that the species name that you entered within the upload form will not be visible in the IDENTIFY tab because we are trying to crowdsource identification. This is to promote skills-sharing and learning. If you are an experienced naturalist, then please don’t worry – your field identification will remain associated with the biological record.</p> 
                 <p>Images will not be published anywhere other than the Orchid Observers website without your express permission.</p> 
                 <p>By uploading field data to Orchid Observers you agree that verified records will be shared with the <a href="http://www.bsbi.org.uk">Botanical Society of the British Isles</a> to aid their research and contribute to national species distribution maps.</p>
                 
                 '''
