module.exports = '''
                 <p>The UK’s environment is constantly changing and most scientists agree that much of the current change is due to human activity. Understanding how the living world is being affected by these changes is an important step in helping us to understand how future environmental change may affect us, our food sources and wildlife. One way of understanding these changes is by documenting when in the year plants and animals respond to changes in the season; well-known examples of this include the timing of frogs spawning in spring or fungi fruiting in autumn. The study of these types of event is called phenology. Natural History Museum scientists are studying the phenology of several groups of UK organism including butterflies, bees, dragonflies, midges, grassland plants and, of course, orchids.  Scientists already know that at least one UK orchid, the Early Spider-orchid (<cite>Ophrys sphegodes</cite>) flowers, on average, several days a year earlier than it did at the start of last century. We aim to join data gathered from historic museum specimens with modern observations made by the public to build a picture of how 29 of our orchid species are adapting to change.</p>

                 <p>So, why are we working on orchids? First, they are much loved and charismatic plants, some of which are declining – even in well protected sites such as nature reserves, other species such as the Pyramidal Orchid (<cite>Anacamptis pyramidalis</cite>) appear to be spreading and increasing in abundance. Understanding how changes in the environment are affecting orchids may help us plan and protect key populations or areas. Another reason why we have chosen orchids is that their flowering season tends to be short compared to other plants and they do not repeat flower – this makes data analysis easier!  In the longer term, museum scientists aim to compare data across a wider range of plant and animal groups and investigate how certain habitats are responding to change; a major concern is that certain species that are dependent upon others may not be responding in the same manner or at the same pace. A recent example of this is a study that shows that Blue Tit egg-laying and the rearing of young is not happening at the same pace as the emergence of their main food, aphids.</p>

                 <p>Useful links:</p>

                 <p><a href="http://www.naturescalendar.org.uk/">Nature's Calendar</a></p>

                 <p><a href="http://www.nhm.ac.uk/research-curation/research/research-initiatives/origins-evolution/team/index.html">NHM: Origins and evolution initiative team</a></p>

                 <p><a href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2745.2010.01727.x/abstract">Validation of biological collections as a source of phenological data for use in climate change studies: a case study with the orchid <cite>Ophrys sphegodes</cite></a></p>
                 '''
