module.exports = '''
                  <h2>The science</h2>
                 <p>The UK’s environment is constantly changing and most scientists agree that much of the current change is due to human activity. Understanding how the living world is being affected by these changes is an important step in helping us to understand how future environmental change may affect us, our food sources and wildlife. One way of understanding these changes is by documenting when in the year plants and animals respond to changes in the season; well-known examples of this include the timing of frogs spawning in spring or fungi fruiting in autumn. The study of these types of event is called phenology. Natural History Museum scientists are studying the phenology of several groups of UK organism including butterflies, bees, dragonflies, midges, grassland plants and, of course, orchids. Scientists already know that at least one UK orchid, the Early Spider-orchid (<cite>Ophrys sphegodes</cite>) flowers, on average, several days a year earlier than it did at the start of last century. We aim to join data gathered from historic museum specimens with modern observations made by the public to build a picture of how 29 of our orchid species are adapting to change.</p>
                 <p>So, why are we working on orchids? First, they are much loved and charismatic plants, some of which are declining – even in well protected sites such as nature reserves. Other species such as the Pyramidal Orchid (<cite>Anacamptis pyramidalis</cite>) appear to be spreading and increasing in abundance. Understanding how changes in the environment are affecting orchids may help us plan and protect key populations or areas. Another reason why we have chosen orchids is that their flowering season tends to be short compared to other plants and they do not repeat flower – this makes data analysis easier! In the longer term, museum scientists aim to compare data across a wider range of plant and animal groups and investigate how certain habitats are responding to change; a major concern is that certain species that are dependent upon others may not be responding in the same manner or at the same pace. A recent example of this is a study that shows that Blue Tit egg-laying and the rearing of young is not happening at the same pace as the emergence and peak abundance of their main food, caterpillars.</p>
                 <p>As well as aiming to learn more about the phenological response of the UK’s orchids to environmental change, we hope that this project will add to our understanding of UK orchid distribution and population health more widely. Verified orchid records collected through this project will support the research activity of the Botanical Society of Britain and Ireland (BSBI), the leading society in Britain &amp; Ireland for the study of plant distribution and taxonomy. An army of volunteer naturalists has been making observations of the UK’s wildlife for well over a hundred years and these observations form the basis of our understanding of which plants, animals and fungi occur in the UK, where they can be found and how their distributions are changing through time. Like other volunteer recording schemes, the BSBI plays a key role in generating and collating these records. It also develops and communicates understanding of the UK’s botanical diversity.</p>
                 If you are interested in learning more about the UK’s botanical diversity, or wish to continue your citizen science activity by getting involved in biological recording, then why not join your local natural history society, or one of the UK’s fantastic amateur-expert recording schemes.

                 <p>Useful links:</p>

                 <p><a href="http://www.naturescalendar.org.uk/">Nature's Calendar</a></p>

                 <p><a href="http://www.nhm.ac.uk/research-curation/research/research-initiatives/origins-evolution/team/index.html">NHM: Origins and evolution initiative team</a></p>

                 <p><a href="http://onlinelibrary.wiley.com/doi/10.1111/j.1365-2745.2010.01727.x/abstract">Validation of biological collections as a source of phenological data for use in climate change studies: a case study with the orchid <cite>Ophrys sphegodes</cite></a></p>
                 <p><a href="http://www.bsbi.org.uk">Botanical Society of Britain and Ireland</a></p>
                 <p><a href="https://www.brc.ac.uk/recording-schemes">Biological Records Centre: recording schemes</a></p>
    
    <p><cite>‘Orchid Observers’</cite> is funded by the <a href="http://www.ahrc.ac.uk/">Arts and Humanities Research Council</a> (Science in Culture theme), as part of <a href="http://conscicom.org/">Constructing Scientific Communities.</a></p>
                 '''
